name: Run Cypress Tests on Multiple Browsers

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    strategy:
      matrix:
        browser: [chrome, firefox, edge]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOTTOKEN }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci  # Install dependencies from package-lock.json
    
    - name: Clean Screenshots Folder
      run: |
        if [ -d "cypress/screenshots" ]; then
          rm -rf cypress/screenshots
        fi
    
    - name: Install Cypress
      run: npm install cypress --save-dev  # Install Cypress as a dev dependency

    - name: Run Cypress tests
      run: npx cypress run --spec 'cypress/e2e/'  # Runs all tests in the e2e folder

    

    - name: Run Cypress Tests on ${{ matrix.browser }}
      env:
        BROWSER: ${{ matrix.browser }}
      run: |
        npx cypress run --browser $BROWSER --headless --spec 'cypress/e2e/'

    - name: Commit and Push Screenshots
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://github.com/${{ github.repository }}.git
        git add cypress/screenshots
        git commit -m "Add Cypress screenshots for ${{ matrix.browser }}"
        git push
      if: success()  # Commit only if tests succeeded

